# Generated by Django 3.0.5 on 2020-07-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coursemodel',
            fields=[
                ('course_name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('faculty', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('fee', models.FloatField(max_length=10)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Studentmodel',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('emailid', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('student_course', models.ManyToManyField(to='app.Coursemodel')),
            ],
        ),
    ]
